inherit_from: .rubocop_todo.yml
require: rubocop-rails
AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 6.0
  Exclude:
    - config/environments/*
    - db/**/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - tmp/**/*
    - bin/**/*
    - vendor/**/*
