:schedule:
  monthly_reward:
    cron: '0 0 1 * *'
    class: MonthlyRewardJob

  quarterly_reward:
    cron: '0 0 1 */3 *'
    class: QuarterlyRewardJob

  expire_point:
    cron: '0 0 1 1 *'
    class: ExpirePointJob

